### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by ashander** [tskit-dev/administrative#1]
It would be nice to have one other than the GH default

**Comment by ashander** [comment]
We're going with @petrelharp 's version (see #3 ) maybe when @jeromekelleher is back he can change the Organization icon/logo/avatar on github

**Comment by jeromekelleher** [comment]
It would be good to add the actual source here for @petrelharp's awesome logo. Would you mind opening a PR (or just pushing to master) the inkscape file and and SVG version of the logo please @petrelharp?

**Comment by petrelharp** [comment]
done (on master). feel free to make adjustments/suggestions: I did this in 5 minutes.

**Comment by jeromekelleher** [comment]
I'm not seeing this on master @petrelharp --- did you push it to your fork maybe?

**Comment by petrelharp** [comment]
Whoops: I put it here: https://github.com/petrelharp/ftprime_ms/blob/master/tskit_logo.ink.svg  =)

**Comment by petrelharp** [comment]
NOW it's there. =)

**Comment by hyanwong** [comment]
My friend has got back with a few logo designs based on what we had. The last one misses the point a little, I think. But the other seem good to me. Opinions welcome (and these are only first drafts). I can get these as SVGs too.

@petrelharp might like to comment? :)

[edit - extra version added as 1b]
<table border=1><tr><td>1 (a & b)<br>
<img width="300" alt="pastedgraphic-8" src="https://user-images.githubusercontent.com/4699014/51836188-909d3880-22f7-11e9-8791-30d77ec393ad.png"><img width="300" alt="pastedgraphic-13" src="https://user-images.githubusercontent.com/4699014/51853214-a3c3fe80-231f-11e9-984f-5cfbaed40b70.png">

</tr></td><tr><td>2<br>
<img width="383" alt="pastedgraphic-9" src="https://user-images.githubusercontent.com/4699014/51836229-ba565f80-22f7-11e9-954f-6d587ab6b19d.png">

</tr></td><tr><td>3<br><img width="330" alt="pastedgraphic-11" src="https://user-images.githubusercontent.com/4699014/51836237-c04c4080-22f7-11e9-99ce-e058fc9d8cc4.png">
</tr></td></table>

**Comment by jeromekelleher** [comment]
I love them all! I'll need to think about it to see which one I like best. 

Pinging @tskit-dev/all for opinions!

**Comment by andrewkern** [comment]
agree this are all great! i guess if i had to choose, the first one speaks to me

**Comment by JereKoskela** [comment]
I also prefer the first one. I think the third suffers a little from depicting a single tree, rather than a tree sequence.

**Comment by hyanwong** [comment]
For pronunciation and etymological reasons, I find the first one helpful in that the "ts" is separated from "kit". So it's clear that the library is ts-kit, not t-skit, or [t]skit with a silent t.

(I guess this is very lightly implied in the second logo, since "ts" is part of the first tree, and "kit" is part of the second).

**Comment by hyanwong** [comment]
Oh, and if the long branch were to also be present on the RHS tree (rightmost branch) in logo 1, then it would be clear that the order of the branches was the same, and the topology had changed. Come to think of it, it might be possible to drop the middle branch a little lower (but to the same height on each tree), so that it replaced the dot over the 'i', as done as part of the 3rd logo. If all the tips are at slightly different heights in a tree (but the same between trees) it makes the topology point very explicitly.

I'd have to ask my logo-designing friend if this would work, visually, though.

**Comment by hyanwong** [comment]
I've just added another version of logo 1 with different branch lengths, as I mentioned in the comment above this one. I changed the original comment, rather than adding a new one below, as I think it's easier to see all the logo possibilities together.

**Comment by petrelharp** [comment]
Wow, those are great! I also vote for 1(b). (Visually, I like 1(a) a bit better, but those are good conceptual points you have.)

**Comment by hyanwong** [comment]
@petrelharp thanks. If you can figure out quite what it is that you prefer visually about 1a) vs 1b) I can relay it on and see if there's a best-of-both option.

**Comment by petrelharp** [comment]
I think mostly the dot on the "i". Which would actually be there, as a colored-in circle on the tip of the branch.

**Comment by hyanwong** [comment]
@petrelharp True. Dots at the end of the branches might work. I'll ask.

**Comment by DomNelson** [comment]
Very nice!! I vote for 1a personally. Somehow I find the trailing branch of 1b distracting, so I'm willing to sacrifice a bit of topological correctness for it to be more compact. I do like the branch separating ts/kit though so I wouldn't just shorten all of them.

Just my two cents! They're all great, 1b included.

**Comment by gtsambos** [comment]
Another for the (1) designs from me. I like the fact that the dot of the 'i' is shown in (a), but otherwise I prefer (b)  - the lengths of the trailing leaves and the slightly thicker edges look just right to me in that one.

**Comment by hyanwong** [comment]
A couple of simple changes to 1b, just to get some feedback. My friend says he thinks dots on all the tips is probably too fussy.

![image](https://user-images.githubusercontent.com/4699014/51867814-5b6b0780-2344-11e9-80e8-974457a96032.png)

![image](https://user-images.githubusercontent.com/4699014/51867831-6887f680-2344-11e9-9050-9761ef2baceb.png)

**Comment by molpopgen** [comment]
I'm partial to 1a, with dot.

**Comment by DomNelson** [comment]
I agree that the width of the branches in 1b is nice

**Comment by hyanwong** [comment]
Or of course: 

<img width="300" alt="pastedgraphic-8" src="https://user-images.githubusercontent.com/4699014/51868211-65d9d100-2345-11e9-9a68-95d19b323605.png">

**Comment by gtsambos** [comment]
Cool! My new vote is for 1(c) (pale green dot on the i only).

**Comment by petrelharp** [comment]
I also like the most recent one (dark dot on the 'i').

**Comment by hyanwong** [comment]
Splitting the difference is nice too (I should stop playing now, though!) ![screenshot 2019-01-28 at 21 47 30](https://user-images.githubusercontent.com/4699014/51868614-560ebc80-2346-11e9-9e31-8ce7cb2d7d8b.png)

**Comment by hyanwong** [comment]
So here's roughly where we are, choice wise. I've added an extra 2b in the same style as the 1b we were discussing. I actually prefer a font which allows the trailing branch on the RHS not to be miles off the end of the text, and I slightly dislike the fact that the trees are different widths in 1b. So perhaps a font change on option (1) might be an option worth exploring too.


<table border=1><tr><td>1 (a & b)<br>
<img width="300" alt="pastedgraphic-8" src="https://user-images.githubusercontent.com/4699014/51836188-909d3880-22f7-11e9-8791-30d77ec393ad.png"><img width="170" alt="pastedgraphic-13" src="https://user-images.githubusercontent.com/4699014/51868614-560ebc80-2346-11e9-9e31-8ce7cb2d7d8b.png">

</tr></td><tr><td>2 (a & b)<br>
<img width="383" alt="pastedgraphic-9" src="https://user-images.githubusercontent.com/4699014/51836229-ba565f80-22f7-11e9-954f-6d587ab6b19d.png">

<img width="220" alt="pastedgraphic-9" src="https://user-images.githubusercontent.com/4699014/51893187-1672bf80-239c-11e9-9e8b-7d8157eb89f0.png">

**Comment by jeromekelleher** [comment]
These look great, thanks for all the work @hyanwong!

My 10c is I prefer 1b and 2b --- having a separator between ts and kit helps to discourage people thinking it's pronounced t-skit, as you pointed out. I prefer having the tree branch not quite reaching the bottom line. I'm not keen on the dot above the "i" being part of the tree though. To me this make it look like the samples in the two trees are different: what does this signify in the tree?

**Comment by hyanwong** [comment]
I find it a nice conceit to link in the 'i' dot to the tree (personally, I like it graphically) but you are right it's a little confusing that there isn't one in the same place on the left hand tree too. I tried that in my [comment above](
https://github.com/tskit-dev/administrative/issues/1#issuecomment-458310216): would something like that satisfy you. Or are you also worried that there is no reason to pick it out over the other two branches? It could, perhaps, indicate that this is the branch that has moved?

**Comment by hyanwong** [comment]
[or perhaps if the dot is solid blue for 1b, or solid white for 2b, it won't look quite so much like an integral part of the tree, more like an incidental overlap of the text and the tree branch]

**Comment by jeromekelleher** [comment]
I agree it looks nice. Personally I'd prefer the two-dot version, but I'm probably being over-literal about interpreting the trees.

**Comment by hyanwong** [comment]
@jeromekelleher : something like this matches the half-closed interval [a,b) used in the ts notation. Imagine a horizontal line being drawn between the two circular nodes - that's +- the edge. Bonus points here I reckon for getting in SPRs and edge spans!

![image](https://user-images.githubusercontent.com/4699014/51916094-7edd9300-23d4-11e9-8207-8e47bafe7a0c.png)

(perhaps I'm being even more literal)

**Comment by jeromekelleher** [comment]
That's pretty cool!

**Comment by hyanwong** [comment]
I suspect this style ticks most boxes for most people who have weighed in so far. So I'll go back to the designer with the basic idea and ask about fonts, alignment, etc., then feed back here.

**Comment by hyanwong** [comment]
[Now I'm getting silly - I'm not actually suggesting this as a logo. But I though people here might appreciate it]

![image](https://user-images.githubusercontent.com/4699014/51931881-d04a4a00-23f5-11e9-9f99-ddc830dd097c.png)

**Comment by petrelharp** [comment]
sweeeeet.

**Comment by hyanwong** [comment]
@tskit-dev/all : here's a version of the 2D logo with a font that spaces a little more evenly, so that the two trees can be of the same width (personally, I don't like the font as much, but it's worth seeing what other people here think). The designer thinks that there might actually be some milage in the idea of making a 3D-style logo. What do other people think? Is it worth having a shot at this too?

<img width="431" alt="pastedgraphic-7" src="https://user-images.githubusercontent.com/4699014/52340697-5d019300-2a08-11e9-8dfb-5ff4cd7aa690.png">

**Comment by jeromekelleher** [comment]
I really like this one. We'll need a small logo for things like GitHub, and I don't think 3D would work there. Might be cool to have a 3D one as well though, if your friend doesn't mind playing around with it!

**Comment by petrelharp** [comment]
I also really like it, but the previous version, with the nicer font. It doesn't bother me that trees are different widths - they span different lengths of the genome, anyways. =)  And, I won't oppose people using a 3D model, but I probably won't use it, either.

**Comment by jeromekelleher** [comment]
I don't really mind about the fonts or the spacing, happy to go with what other people think.

**Comment by petrelharp** [comment]
I should have said: I'm also very happy with any of these, but asked for an opinion, I'll give one... =)
