### ISSUE TITLE
style/convention guide as vocab-like "TICL list"

### ISSUE THREAD

**Issue by castedo** [tskit-dev/administrative#12]
@jeromekelleher Here's the idea I mentioned ... and an answer to your question about `double const *` vs `const double *` ... via 'TICL #101'. :)

The idea is to have something where:

1. you and others can link to a specific "TICL" in code reviews ... i.e. "regarding code XYZ blah blah see TICL 123"
2. skips having to re-type reasoning in threads
3. less prescriptive about what language use is right/wrong and more about what meaning the most active readers of tskit-dev code interpret from certain expressions/patterns of C or Python code
4. something that feels more fun than a prohibition or ban
5. good exercise to think critically about what a style/convention is actually trying to accomplish
6. avoid blind following of consistency just for the sake of consistency
7. facilitates community learning of some languages features that might be new or unfamiliar

So here's a start (and answer to your earlier question):

https://github.com/castedo/administrative/blob/vocab_idea/development/code_vocabulary.md

Anyway, I thought you might find it or something that it evolves into useful.

**Comment by jeromekelleher** [comment]
Very good, thanks @castedo. It's a bit like (pep8)[https://www.python.org/dev/peps/pep-0008/] for tskit C code. We do have a bit of this type of documentation [here](https://tskit.readthedocs.io/en/latest/development.html#coding-conventions) and [here](https://tskit.readthedocs.io/en/latest/c-api.html#api-structure) but it's not at the level of detail you're thinking about.

> avoid blind following of consistency just for the sake of consistency

But... that would be inconsistent! :exploding_head:

**Comment by castedo** [comment]
A possibility is that when there is a TICL that covers specific points made redundantly in both
  https://tskit.readthedocs.io/en/latest/development.html#coding-conventions
and
  https://msprime.readthedocs.io/en/stable/development.html#coding-conventions
then those two places could reference the appropriate TICL.

@jeromekelleher What are your thoughts on the long term plan for those two doc sections which are more or less copies?

I am imagining a **flat directory**, somewhere, which has a dump of **one file per TICL**. Then those individual TICL pages can be referenced from many places:
* coding convention pages across diff tskit-dev repositories
* code review threads
* inside code comments
* wider discussions and communications

A kind of glossary/dictionary/lexicon/guide on code language understanding in tskit-dev.

**Comment by petrelharp** [comment]
This is interesting, and I like the motivation. I haven't formed an opinion about it.  But, a couple of observations. A lengthy style guide could feel overwhelming to new folks (eg, feeling like they need to memorize the entire thing before contributing), and also, maintaining it could be a significant distraction for the rest of us. I'd suggest at least surveying some less experienced contributors to see if they think it's a good idea.

**Comment by molpopgen** [comment]
I agree that conventions need to be agreed upon, but I agree with @petrelharp that things like this can make the docs overwhelming.

I think the following statements probably covers almost everything:

```
C code should be written in C99, with the exception that variable declarations must take place at the top of a function's scope.
```

For example, the right to left reading of const has nothing to do with tskit.  Rather, that's just how C is.  We don't want to confuse anyone by accidentally implying that one of these items is somehow not already covered in the C language.

The only real tskit-specific thing that I see is that const-correctness is not currently part of the coding convention, which can trip up c++ programmers. (I often have to cast away const--ness when interacting with tskit, for example.)

**Comment by castedo** [comment]
Thanks for y'all's comments!

What I'm thinking now is that this TICL list idea, if it were commited in a tskit-dev repository, is too easily interpreted (oh the irony!) as a kind mandated convention that everybody must know, follow and agree upon. But I was exploring this idea as something different than mandated conventions. Something more in the spirit of documenting what "pants" means in the UK vs US and not saying which interpretation is correct or not.

And I also don't want it to become distracting for people who don't find it interesting or helpful.

At least initially, I think I should document these observations as my own notes that I'll share with everybody. But I can just do that in a new repository I create. 

In general, I haven't quite figured out where to put stuff that I create relating to tskit-dev that may or may not be interesting or useful to other tskit devs.

**Comment by jeromekelleher** [comment]
Thanks for the comments here guys, this is very helpful. Re const correctness @molpopgen, I'm definitely open to doing this properly, it's just something I've never gotten the hang of. Might be something to add to the list for tskit C 1.0?

**Comment by castedo** [comment]
I added https://github.com/tskit-dev/tskit/issues/844 and some thoughts regarding const and the tskit C API.
